---
version: '3.8'
networks:
 roboshop:
  driver: bridge
services:
 mongodb:
  image: sivadevops1014/mongodb:v1
  container_name: mongodb
  networks:
   - roboshop
 catalogue:
  image: sivadevops1014/catalogue:v1
  container_name: catalogue
  networks:
   - roboshop
  depends_on:
   - mongodb
 redis:
  image: redis
  container_name: redis
  networks:
   - roboshop
 user:
  image: sivadevops1014/user:v1
  container_name: user
  networks:
   - roboshop
  depends_on:
   - redis
   - mongodb
 cart:
  image: sivadevops1014/cart:v1
  container_name: cart
  networks:
   - roboshop
  depends_on:
   - redis
   - catalogue
 mysql:
  image: sivadevops1014/mysql:v1
  container_name: mysql
  networks:
   - roboshop
 shipping:
  image: sivadevops1014/shipping:v1
  container_name: shipping
  networks:
   - roboshop
  depends_on:
   - cart
   - mysql
 rabbitmq:
  image: rabbitmq
  container_name: rabbitmq
  networks:
   - roboshop
  environment:
   - RABBITMQ_DEFAULT_USER=roboshop
   - RABBITMQ_DEFAULT_PASS=roboshop123
 payment:
  image: sivadevops1014/payment:v1
  container_name: payment
  networks:
   - roboshop
  depends_on:
   - cart
   - user
   - rabbitmq
 web:
  image: sivadevops1014/web:v1
  container_name: web
  networks:
   - roboshop
  ports:
   - "80:80"
  depends_on:
   - catalogue
   - user
   - cart
   - shipping
   - payment
...