---
version: '3.8'
networks:
 roboshop:
  driver: bridge
services:
 mongodb:
  image: mongodb:v1
  container_name: mongodb
  networks:
   - roboshop
 catalogue:
  image: catalogue:v1
  container_name: catalogue
  networks:
   - roboshop
  depends_on:
   - mongodb
 redis:
  image: redis
  networks:
   - roboshop
...