---
version: '3.8'
networks:
 roboshop:
  driver: bridge
services:
 mongodb:
  image: mongodb:v1
  container_name: mongodb
  networks:
   - roboshop
 catalogue:
  image: catalogue:v1
  container_name: catalogue
  networks:
   - roboshop
  depends_on:
   - mongodb
 redis:
  image: redis
  container_name: redis
  networks:
   - roboshop
 user:
  image: user:v1
  container_name: user
  networks:
   - roboshop
  depends_on:
   - redis
   - mongodb
 cart:
  image: cart:v1
  container_name: cart
  networks:
   - roboshop
  depends_on:
   - redis
   - catalogue
...